package com.example.cook.post;

public enum Time {
    _5_MINUTES_OR_LESS, _10_MINUTES_OR_LESS, _15_MINUTES_OR_LESS, _20_MINUTES_OR_LESS, _30_MINUTES_OR_LESS, _60_MINUTES_OR_LESS, _90_MINUTES_OR_LESS, _2_HOURS_OR_LESS, _MORE_THAN_2_HOURS
}
